/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mavenproject4.UI;

import com.mycompany.mavenproject4.Premios;
import com.mycompany.mavenproject4.ServicioAplicacion;
import com.mycompany.mavenproject4.SideMenuPanel;
import com.mycompany.mavenproject4.Usuario;
import com.mycompany.mavenproject4.UsuarioPerteneceFamilia;
import com.mycompany.mavenproject4.UsuarioReclamaPremios;
import com.mycompany.mavenproject4.UsuarioReclamaPremiosId;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author tetra
 */
public class FramePremiosDeFamilia extends javax.swing.JFrame {

    private final SideMenuPanel sp;
    private int menuInt = 1;
    private final UsuarioPerteneceFamilia upf;
    private final int idFamilia;
    private final ServicioAplicacion servicio;
    private final Usuario usuarioLogeado;

    /**
     * Creates new form FramePremiosDeFamilia
     */
    public FramePremiosDeFamilia(Usuario usuarioLogeado, UsuarioPerteneceFamilia upf) throws Exception {
        initComponents();
        this.usuarioLogeado = usuarioLogeado;
        this.servicio = new ServicioAplicacion();
        this.upf = upf;
        idFamilia = upf.getIdFamilia();
        sp = new SideMenuPanel(this);
        sp.setMain(mainPanel);
        sp.setSide(sidebar);
        sp.setMinWidth(50);//borde restante al ocultar
        sp.setMaxWidth(160);//cuanto ocupa abierto
        sp.setMainAnimation(false);
        sp.setSpeed(0);
        sp.setResponsiveMinWidth(600);
        sp.openMenu();
        updatePremiosActivosTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        sidebar = new javax.swing.JPanel();
        BtnMenu = new javax.swing.JButton();
        BtnTareas = new javax.swing.JButton();
        BtnPremios = new javax.swing.JButton();
        BtnTareasEntregadas = new javax.swing.JButton();
        BtnCambiarFam = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();
        BtnNotis = new javax.swing.JButton();
        BtnPremiosAct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabPremiosActivos = new javax.swing.JTable();
        BtnDesactivarPremio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        sidebar.setBackground(new java.awt.Color(0, 30, 54));
        sidebar.setToolTipText("");

        BtnMenu.setBackground(new java.awt.Color(0, 30, 54));
        BtnMenu.setForeground(new java.awt.Color(0, 30, 54));
        BtnMenu.setIcon(new javax.swing.ImageIcon("C:\\Users\\tetra\\Desktop\\tfg\\Persistencia-BranchDeMartinMVAR\\Persistencia-BranchDeMartinMVAR\\mavenproject4\\src\\main\\java\\com\\mycompany\\mavenproject4\\imgs\\menu_15.png")); // NOI18N
        BtnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuActionPerformed(evt);
            }
        });

        BtnTareas.setBackground(new java.awt.Color(0, 30, 54));
        BtnTareas.setForeground(new java.awt.Color(255, 255, 255));
        BtnTareas.setText("Tareas");
        BtnTareas.setMaximumSize(new java.awt.Dimension(114, 23));
        BtnTareas.setMinimumSize(new java.awt.Dimension(114, 23));
        BtnTareas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTareasActionPerformed(evt);
            }
        });

        BtnPremios.setBackground(new java.awt.Color(0, 30, 54));
        BtnPremios.setForeground(new java.awt.Color(255, 255, 255));
        BtnPremios.setText("Premios");
        BtnPremios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPremiosActionPerformed(evt);
            }
        });

        BtnTareasEntregadas.setBackground(new java.awt.Color(0, 30, 54));
        BtnTareasEntregadas.setForeground(new java.awt.Color(255, 255, 255));
        BtnTareasEntregadas.setText("Tareas Hechas");
        BtnTareasEntregadas.setMaximumSize(new java.awt.Dimension(114, 23));
        BtnTareasEntregadas.setMinimumSize(new java.awt.Dimension(114, 23));
        BtnTareasEntregadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTareasEntregadasActionPerformed(evt);
            }
        });

        BtnCambiarFam.setBackground(new java.awt.Color(0, 30, 54));
        BtnCambiarFam.setForeground(new java.awt.Color(255, 255, 255));
        BtnCambiarFam.setIcon(new javax.swing.ImageIcon("C:\\Users\\tetra\\Desktop\\tfg\\Persistencia-BranchDeMartinMVAR\\Persistencia-BranchDeMartinMVAR\\mavenproject4\\src\\main\\java\\com\\mycompany\\mavenproject4\\imgs\\home (Custom).png")); // NOI18N
        BtnCambiarFam.setText("Cambiar familia");
        BtnCambiarFam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCambiarFamActionPerformed(evt);
            }
        });

        BtnCerrarSesion.setBackground(new java.awt.Color(0, 30, 54));
        BtnCerrarSesion.setForeground(new java.awt.Color(255, 255, 255));
        BtnCerrarSesion.setIcon(new javax.swing.ImageIcon("C:\\Users\\tetra\\Desktop\\tfg\\Persistencia-BranchDeMartinMVAR\\Persistencia-BranchDeMartinMVAR\\mavenproject4\\src\\main\\java\\com\\mycompany\\mavenproject4\\imgs\\settings (Custom).png")); // NOI18N
        BtnCerrarSesion.setText("Cerrar sesión");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        BtnNotis.setBackground(new java.awt.Color(0, 30, 54));
        BtnNotis.setForeground(new java.awt.Color(255, 255, 255));
        BtnNotis.setText("Notificaciones");
        BtnNotis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnNotisActionPerformed(evt);
            }
        });

        BtnPremiosAct.setBackground(new java.awt.Color(0, 30, 54));
        BtnPremiosAct.setForeground(new java.awt.Color(255, 255, 255));
        BtnPremiosAct.setText("Premios Activos");
        BtnPremiosAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnPremiosActActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarLayout = new javax.swing.GroupLayout(sidebar);
        sidebar.setLayout(sidebarLayout);
        sidebarLayout.setHorizontalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnCerrarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnCambiarFam, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidebarLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtnTareasEntregadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPremios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnTareas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnNotis, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtnPremiosAct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        sidebarLayout.setVerticalGroup(
            sidebarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtnTareas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnTareasEntregadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPremios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnPremiosAct)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtnNotis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnCambiarFam)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 30, 54));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PREMIOS ACTIVOS");

        jScrollPane1.setBackground(new java.awt.Color(226, 226, 226));

        TabPremiosActivos.setBackground(new java.awt.Color(226, 226, 226));
        TabPremiosActivos.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 14)); // NOI18N
        TabPremiosActivos.setForeground(new java.awt.Color(0, 30, 54));
        TabPremiosActivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Usuario", "Premio", "Reclamado", "Tiempo restante", "Id", "Dni"
            }
        ));
        jScrollPane1.setViewportView(TabPremiosActivos);

        BtnDesactivarPremio.setBackground(new java.awt.Color(0, 30, 54));
        BtnDesactivarPremio.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BtnDesactivarPremio.setForeground(new java.awt.Color(255, 255, 255));
        BtnDesactivarPremio.setText("Desactivar");
        BtnDesactivarPremio.setToolTipText("");
        BtnDesactivarPremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDesactivarPremioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(sidebar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 632, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnDesactivarPremio, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidebar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnDesactivarPremio, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuActionPerformed
        if (this.menuInt == 0) {
            sp.openMenu();

            this.BtnPremios.setVisible(true);
            this.BtnCambiarFam.setVisible(true);
            this.BtnCerrarSesion.setVisible(true);
            this.BtnTareas.setVisible(true);
            this.BtnTareasEntregadas.setVisible(true);
            this.BtnNotis.setVisible(true);
            this.BtnPremiosAct.setVisible(true);

            this.menuInt = 1;
        } else {
            sp.closeMenu();
            this.BtnPremios.setVisible(false);
            this.BtnCambiarFam.setVisible(false);
            this.BtnCerrarSesion.setVisible(false);
            this.BtnTareas.setVisible(false);
            this.BtnTareasEntregadas.setVisible(false);
            this.BtnNotis.setVisible(false);
            this.BtnPremiosAct.setVisible(false);
            this.menuInt = 0;

        }
    }//GEN-LAST:event_BtnMenuActionPerformed

    private void BtnTareasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTareasActionPerformed
        new FramePantallaPrincipal(upf, usuarioLogeado).setVisible(true); //
        this.dispose();
    }//GEN-LAST:event_BtnTareasActionPerformed

    private void BtnPremiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPremiosActionPerformed
        new FramePremiosPantalla(upf, usuarioLogeado).setVisible(true); //
        this.dispose();
    }//GEN-LAST:event_BtnPremiosActionPerformed

    private void BtnTareasEntregadasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTareasEntregadasActionPerformed
        new FrameTareasHechas(upf, usuarioLogeado).setVisible(true); //
        this.dispose();
    }//GEN-LAST:event_BtnTareasEntregadasActionPerformed

    private void BtnCambiarFamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCambiarFamActionPerformed
        new FrameListaFams(usuarioLogeado.getDni()).setVisible(true); //
        this.dispose();
    }//GEN-LAST:event_BtnCambiarFamActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        new FrameLogin().setVisible(true); //
        this.dispose();

    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnNotisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnNotisActionPerformed
        new FrameNotificaciones(upf, usuarioLogeado).setVisible(true); //
        this.dispose();
    }//GEN-LAST:event_BtnNotisActionPerformed

    private void BtnDesactivarPremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDesactivarPremioActionPerformed
        int selectedRow = TabPremiosActivos.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Seleccione un premio para desactivar.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TabPremiosActivos.getModel();
        String dniUsuario = model.getValueAt(selectedRow, 5).toString();
        String idPremio = model.getValueAt(selectedRow, 4).toString();
        Date fechaReclamado = (Date) model.getValueAt(selectedRow, 2); // Asegúrate de que la fecha se maneje correctamente

        UsuarioReclamaPremiosId urpId = new UsuarioReclamaPremiosId(dniUsuario, idPremio, fechaReclamado);
        UsuarioReclamaPremios premioActivo = servicio.findPremioActivoPorId(urpId);

        if (premioActivo == null) {
            JOptionPane.showMessageDialog(this, "Premio no encontrado o ya no está activo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            // Llamar al método para desactivar el premio
            servicio.deactivatePremio(premioActivo);
        } catch (Exception ex) {
            Logger.getLogger(FramePremiosDeFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }

        JOptionPane.showMessageDialog(this, "Premio desactivado exitosamente.", "Premio Desactivado", JOptionPane.INFORMATION_MESSAGE);

        try {
            // Actualizar la tabla para reflejar el cambio
            updatePremiosActivosTable();
        } catch (Exception ex) {
            Logger.getLogger(FramePremiosDeFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_BtnDesactivarPremioActionPerformed

    private void BtnPremiosActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnPremiosActActionPerformed
        try {
            new FramePremiosActivos(usuarioLogeado, upf).setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(FramePremiosDeFamilia.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.dispose();
    }//GEN-LAST:event_BtnPremiosActActionPerformed
    private void updatePremiosActivosTable() throws Exception {
        String idPremio;
        Premios premioActivoSingular;
        String nombreDelPremio;
        String nombreDelUser;
        Usuario user;
        List<UsuarioReclamaPremios> premiosActivos = servicio.findPremiosActivosPorFamilia(idFamilia);
        DefaultTableModel model = (DefaultTableModel) TabPremiosActivos.getModel();
        model.setRowCount(0); // Clear existing data

        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        for (UsuarioReclamaPremios premioActivo : premiosActivos) {
            idPremio = premioActivo.getIdPremio();
            premioActivoSingular = servicio.findPremioById(idPremio);
            nombreDelPremio = premioActivoSingular.getNombre();
            String fecha = sdf.format(premioActivo.getReclamado());
            String tiempoRestante = calculateRemainingTime(premioActivo.getReclamado(), premioActivoSingular.getDuracion());

            user = servicio.findUsuarioByDni(premioActivo.getDni());
            nombreDelUser = user.getNombre();

            if (tiempoRestante.equalsIgnoreCase("caducado")) {
                servicio.deactivatePremio(premioActivo);
            } else {
                model.addRow(new Object[]{nombreDelUser, nombreDelPremio, fecha, tiempoRestante, idPremio, premioActivo.getDni()});
            }

        }
    }

    private String calculateRemainingTime(Date startDate, int durationDays) {
        // Calculate end time in milliseconds
        long endTimeInMillis = startDate.getTime() + durationDays * 24L * 60 * 60 * 1000;
        long remainingTime = endTimeInMillis - System.currentTimeMillis();

        // Check if the remaining time is negative, indicating expiration
        if (remainingTime <= 0) {
            return "Caducado";
        }

        // Calculate remaining days and hours if not expired
        long days = TimeUnit.MILLISECONDS.toDays(remainingTime);
        long hours = TimeUnit.MILLISECONDS.toHours(remainingTime) % 24;

        return days + " días, " + hours + " horas restantes";
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCambiarFam;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnDesactivarPremio;
    private javax.swing.JButton BtnMenu;
    private javax.swing.JButton BtnNotis;
    private javax.swing.JButton BtnPremios;
    private javax.swing.JButton BtnPremiosAct;
    private javax.swing.JButton BtnTareas;
    private javax.swing.JButton BtnTareasEntregadas;
    private javax.swing.JTable TabPremiosActivos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel sidebar;
    // End of variables declaration//GEN-END:variables
}
